-- Primary keys are UUIDv7 values generated by the application. Because a UUIDv7 starts with its
-- creation time, no created_at column is needed: ordering by id is ordering by creation time.
create table note (
    id    uuid         primary key,
    title varchar(200) not null,
    body  text
);
